### ISSUE TITLE
Voicemaster + Gameserver  Keyfile info

### ISSUE THREAD

**Issue by renegade1337** [easy-wi/installer#108]
Wenn man sich beim installer ein Keyfile generieren lässt, dann wird ganz zum Schluss folgendes ausgegeben:
`Don't forget to copy Keyfile into "/home/easywi_web/keys/"`

Es wäre sicherlich ganz gut wenn man den Text so formulieren würde das man auch weiß welche Datei dort eingefügt werden soll. Sprich z.B. voicemaster oder voicemaster.pub, im falle das man die Datei voicemaster genannt hat. Damit die User wirklich ganz genau wissen welche von den Dateien dort hinzugefügt werden muss.

**Comment by Lacrimosa99** [comment]
Im Script wurde, wenn beides auf dem selben Host liegt, der copy vorgang automatisiert.
somit ist ein kopieren des falschen schlüssels ausgeschlossen.
sollten webinterface und gamemaster getrennt sein, dann zeigt es nun auch die datei an, welche ins webinterface verzeichnis kopiert werden muss.
