### ISSUE TITLE
Easy-wi for Ubuntu 22.04?

### ISSUE THREAD

**Issue by Yzord** [easy-wi/installer#128]
I want to install a CS:GO server on a Ubuntu 22.04 server and after searching on the interweb i came to this project. It looks great at first glance and the install script seems to be a no-brainer, but i have issues (of course, like always).

When it tries to install a SQL server (in this case MariaDB) the error party started. I get this error

`The repository 'https://downloads.mariadb.com/MariaDB/mariadb-10.4/repo/ubuntu jammy Release' does not have a Release file.`

Ah well, no issue, it seems to get it from the Ubuntu archive itself. But then after installing it, i get this error

`Securing MySQL by running "mysql_secure_installation" commands.
./easy-wi_install.sh: line 1216: [: 10.6.11-MariaDB: integer expression expected`

So, as far my knowledge goes, it didn't executed the mysql_secure_installation command, so i think MariaDB isn't secured (yet). Of course i could run it by myself eventually, but just to remind the devs the script is failing (on 22.04).

But the script has no issues with it and goes further with installing the PHP packages. And thats where it all stops. It installs php8.1 first and that seems to be no issue. After that it tries to install the php7.4-common package and there the script stops with the error

`E: Package 'php7.4-common' has no installation candidate`

So, i guess it ends here. Well, i could do it all manually, but it is this stage i am wondering if easy-wi is still supported for latest distro's? Because it seems most repositories are obsolete/old and the script doesn't seems to be updated anymore since a while.

Am i tracing a dead horse here? Is it still usable? Hope i can find some answers here.

Thanks anyway and best wishes for this year.

**Comment by AEon-Jan** [comment]
https://github.com/easy-wi/installer/releases/tag/3.2
