### ISSUE TITLE
Error after installing the Webpanel

### ISSUE THREAD

**Issue by ManfredDoorstander** [easy-wi/installer#139]
Every time i installed the Webpanel and i try to open the website this shows up

"Fatal error: Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/install/install.php:69 Stack trace: #0 {main} thrown in /var/www/html/install/install.php on line 69"

Could someone help because no one on the Discord server is responding

**Comment by Lacrimosa99** [comment]
Please use the developer branch for your concern as this is only for the installer script.
