### ISSUE TITLE
Installing english version

### ISSUE THREAD

**Issue by kristophr** [easy-wi/installer#140]
Ran into two issues while installing

in /home/easy_wi/htdocs/install/languages/en.xml file - there are two tags that do not have a proper closing tag.

<system_check_ok_folder_1>Folder<system_check_ok_folder_1>
<system_check_ok_folder_2>exists and can write to<system_check_ok_folder_2>

I had to manually put the / in the closing tag:

<system_check_ok_folder_1>Folder</system_check_ok_folder_1>
<system_check_ok_folder_2>exists and can write to</system_check_ok_folder_2>

secondly - the part where you fill out your user name to create the server page - there's a field called "give your home page a name" or something like that - I did kris' server and the installer broke all over the place - so some code should be put in to handle these kind of special characters when not expected.  Just FYI.

**Comment by Lacrimosa99** [comment]
Please use the developer branch for your concern as this is only for the installer script.
