### ISSUE TITLE
Repo adoptopenjdk.jfrog.io Deprecated

### ISSUE THREAD

**Issue by Lacrimosa99** [easy-wi/installer#143]
Repository 'adoptopenjdk.jfrog.io' is deprecated and moved to 'adoptium.net'.

Blog Entry: https://adoptium.net/de/blog/2023/07/adoptopenjdk-jfrog-io-has-been-deprecated/

**Comment by Nexus633** [comment]
I can't find adoptopenjdk.jfrog.io in the code. The repository used is adoptium.net. Can you give a line number where you found it? I'd be happy to adjust that.

**Comment by Lacrimosa99** [comment]
I have just checked the code again because I still had adoptopenjdk in the old source code.
I must have changed at some point but not updated the code locally.
