### ISSUE TITLE
php7.0 is not in the repo of ubuntu artful 17.10 

### ISSUE THREAD

**Issue by Allesanddro** [easy-wi/installer#29]

**Comment by ulrichblock** [comment]
What is the package name in 17.10?

**Comment by Allesanddro** [comment]
should be 7.1 [https://i.sandrotracker.biz/1fd045660528d694a6eeb363861e7aa5.png](url)

i can recheck if they added 7.0 now in the artful dist

**Comment by ulrichblock** [comment]
Is there a meta package like "php" ?

**Comment by Lacrimosa99** [comment]
https://wiki.ubuntuusers.de/PHP/

**Comment by Lacrimosa99** [comment]
https://github.com/easy-wi/installer/commit/b763b95af71f189810e999a49be982b6c9c1ea8c
