### ISSUE TITLE
Easy-Wi Auf laufendem System.

### ISSUE THREAD

**Issue by PaDo90** [easy-wi/installer#30]
Hallo, ich möchte das Easy-Wi auf meinem Server installieren (Debian)
Allerdings ist der Server schon komplett mit Plesk, MySQL und Co eingerichtet.
Ich suche nur ein anständiges Webinterface um Gameserver (CS:GO) auf meinem Server zu starten & konfigurieren.

Habe es mit dem normalen Installer probiert, jedoch bekomme ich da die Meldung:
Aborting as the risk of breaking the installed panel Plesk is too high.

Gibt es eine Möglichkeit, wie ich das trotzdem verwenden kann?

Screenshot:
http://prntscr.com/ipc80s

**Comment by Lacrimosa99** [comment]
Es gibt User die es unter Plesk laufen haben... allerdings Supporten wir hier kein Plesk oder dergleichen.
Dazu bitte ins Plesk Forum wenden.

**Comment by gOOvER** [comment]
Dann installiere einfach keinen Webserver, sondern nur die Gameserver. ;)

**Comment by gOOvER** [comment]
Geht ohne Probleme
