### ISSUE TITLE
Debian 9.4 - Web Interface install

### ISSUE THREAD

**Issue by xxxrenegade** [easy-wi/installer#31]
Ich habe Probleme unter Debian 9.4 das Web Interface zu installieren. Die Installation über die Kommandozeile/PuTTY läuft wunderbar durch. [Hier](https://gist.github.com/xxxrenegade/0d010df35dd0f6265e6515e3101a83b1) das gesamte Protokoll. Wenn ich dann allerdings die URL aufrufe, dann ist unter der URL nichts erreichbar. Weder unter der Domain, auch nicht direkt über die IP.

Ich habe das ganze auch mal mit Debian 8 auf dem selben vServer ausprobiert, dort konnte ich dann die URL aufrufen!

**Comment by xxxrenegade** [comment]
Ich konnte das Problem beheben, es wurde keine .crt Datei erstellt. Ich habe folgendes im installer geändert:
`openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout $SSL_DIR/$FILE_NAME.key -out $SSL_DIR/$FILE_NAME.crt -subj "/C=/ST=/L=/O=/OU=/CN=$IP_DOMAIN"`
zu diesem hier:
`openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout $SSL_DIR/$FILE_NAME.key -out $SSL_DIR/$FILE_NAME.crt -subj "/CN=$IP_DOMAIN"`

**Comment by Lacrimosa99** [comment]
https://github.com/easy-wi/installer/commit/b763b95af71f189810e999a49be982b6c9c1ea8c
