### ISSUE TITLE
Centos 7 Support dont working

### ISSUE THREAD

**Issue by josephbr57** [easy-wi/installer#32]
Hello there,

I installed the installation supporting Centos 7 installation, 
Master server is installed, all dependencies are installed but when i try to make game server with user, server dont create user folder and dont cpying master server files to this.

Thanks

**Comment by ulrichblock** [comment]
There is no such thing as CentOS support at the installer.

**Comment by Lacrimosa99** [comment]
https://github.com/easy-wi/installer/commit/a70e247d16d12dfd7d9813c78019ef085abc3372
