### ISSUE TITLE
Debian 9.5 installer 2.4 - Lets Encrypt - (contabo.de)

### ISSUE THREAD

**Issue by xxxrenegade** [easy-wi/installer#40]
Ich habe den neuen installer mal auf meinen contabo.de (VPS L SSD ohne Setup) VPS getestet. Ich habe es zwei mal auf einem frisch Neu installiertem Debian 9.5 System getestet. Einmal mit Nginx und das andere mal mit Apache. Beide male mit SSL und Lets Encrypt. In beiden fällen konnte der Webserver nicht gestartet werden. Und der installer konnte dementsprechend nicht aufgerufen werden!

easy-wi Nginx log
https://gist.github.com/xxxrenegade/94df27f77a24b8bd92ae6b19f1f8bf17

easy-wi Apache log
https://gist.github.com/xxxrenegade/945e3acbecc4e2e053ac15eafe95c59d

**Comment by Lacrimosa99** [comment]
Da muss sich wohl ein kleiner Fehler eingeschlichen haben.
Wird gefixt und danke fürs melden.

**Comment by xxxrenegade** [comment]
Kein Problem ;-) Ich freu mich auf den Fix ;-)

**Comment by Lacrimosa99** [comment]
https://github.com/easy-wi/installer/commit/b6137f52c49d34a37976fba3c90cf865587b6b1e

**Comment by Lacrimosa99** [comment]
Bitte mal testen... Fehler sollten behoben sein.

**Comment by xxxrenegade** [comment]
Läuft in beiden Fällen immer noch nicht :-/

easy-wi Nginx log v2
https://gist.github.com/xxxrenegade/e80bc9233a91ad81a87e93ebdd5b21a1

easy-wi Apache log v2
https://gist.github.com/xxxrenegade/24c4ba0b4f9f3121ca4e871c0462eb3a

**Comment by Lacrimosa99** [comment]
Leider findet er bei dir nicht den Certbot in deinem Repository´s (von Contabo).
Bitte mal die Debian Repository´s nutzen... darin sind auch die Certbots von Lets Encrypt vorhanden.
Alternative mal mit `apt-cache search certbot` suchen lassen und prüfen, ob eine Ausgabe kommt.

**Comment by xxxrenegade** [comment]
`root@vmd26405:~# apt-cache search certbot
certbot - automatically configure HTTPS using Let's Encrypt
letsencrypt - transitional dummy package
python-certbot - main library for certbot
python-certbot-doc - client documentation for certbot
python-certbot-apache - Apache plugin for Certbot
python-certbot-apache-doc - Apache plugin documentation for Certbot
python-certbot-nginx - Nginx plugin for Certbot
python-certbot-nginx-doc - Nginx plugin documentation for Certbot
`

**Comment by Lacrimosa99** [comment]
Sorry war spät gestern und war etwas im Traumland^^
Sollte nun behoben sein.

https://github.com/easy-wi/installer/pull/42
https://github.com/easy-wi/installer/pull/43

**Comment by xxxrenegade** [comment]
[#44](https://github.com/easy-wi/installer/pull/44)

**Comment by Lacrimosa99** [comment]
#44 is not a Bug.
This will not be implemented.

**Comment by xxxrenegade** [comment]
Das ganze hat bei mir allerdings nicht Funktioniert der Webserver (Nginx) wurde so nicht gestartet!

**Comment by Lacrimosa99** [comment]
Bitte zu Fehlern die dazugehörigen logs anhängen.
Fehler konnten nach ausgiebigen Tests nicht mehr festgestellt werden.

**Comment by Lacrimosa99** [comment]
Habe eben nochmals mit Ubuntu getestet und den Fehler dort nachstellen können.
Danke für den Hinweis und wurde fixed.
