### ISSUE TITLE
Proper English Translation

### ISSUE THREAD

**Issue by alpinethegreat** [easy-wi/installer#53]
I've rewritten the English translation to be more precise and to fix grammar and spelling mistakes. I've attached the lang folder. It's worth mentioning that "uk" should instead be "en".
[fixedlang.zip](https://github.com/easy-wi/installer/files/2612103/fixedlang.zip)

**Comment by Lacrimosa99** [comment]
pls wite this in the right section ;)
https://github.com/easy-wi/developer/issues

We will implement this and thanks =)

**Comment by Lacrimosa99** [comment]
https://github.com/easy-wi/developer/commit/bb975a522dd188e84f573d7f2d0267eaac0acd5d
