### ISSUE TITLE
Masterserver Steam kein download

### ISSUE THREAD

**Issue by BeG1990** [easy-wi/installer#62]
Hallo zusammen,

ich habe zum ausprobieren auf meinem vServer mit Debian Easy-Wi installiert. Zuerst das Webinterface dann den Gameroot (beides auf der selben Maschine). Nachdem mir das alles super gefiel habe ich das Webinterface separat auf meinem Webspace bei einem anderen hinter installiert. Den vorherigen vServer wo beides drauf lief habe neu installiert und nur die Gameroot Geschichte installiert. Nachdem auf dem vServer jetzt nur der Gameroot installiert wurde habe ich allerdings das Problem das wenn ich den Gameroot ins Webinterface als master Einträge und dann zum Beispiel Counterstrike source darauf anlege er wohl den Ordner CSS erstellt dieser allerdings leer bleibt. 
Hoffe ich konnte es einigermaßen verständlich erklären.
Kann es was damit zu tun haben das vorher als das Webinterface auch auf dem vServer war irgendwelche Sachen mitinstalliert wurden und das es deswegen ging und dem Gameroot diese Sachen jetzt fehlen ? Habe nämlich was von binarys gelesen aber wollte lieber mal nachhaken ob da was dran sein könnte.

Liebe Grüße

**Comment by Lacrimosa99** [comment]
Entschuldige das ich jetzt erst zurück schreibe.
Zu deinem Problem... wurde der Gameroot per EasyWI-Installier vorbereitet oder wurde einfach der Gameroot ins WI-Panel eingetragen?

**Comment by BeG1990** [comment]
Hi garkein Problem :) Er wurde via Installer als Gameroot vorbereitet. Komisch war halt das es bei der ersten Installation ging und nachdem ich den Server einmal komplett neu aufgesetzt habe (sprich Debian neu drauf) ging es nicht mehr deswegen die Vermutung mit den Abhängigkeiten. Habe das Problem für mich allerdings lösen können in dem ich nun Ubuntu statt Debian als OS einsetze.

Liebe Grüße

**Comment by Lacrimosa99** [comment]
ok dann wurde das Problem gelöst.
Sollten weiterhin fragen bestehen, so sind wir im Discord und Gitter aktiv ;)
