### ISSUE TITLE
WebPanel Datenbank-User

### ISSUE THREAD

**Issue by Mitleidleggins** [easy-wi/installer#71]
System: Debian Stretch
Datenbank: mariadb-server (Version: mariadb  Ver 15.1 Distrib 10.1.38-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2)
Vor dem EW-Installer installiert.
EW-Installer Version: 2.3 Stable

Beschreibung:
Hallo, soeben wollte ich eine Neuinstallation vom WebPanel machen machen. Wurde aufgefordert das Kennwort für den EasyWi-Datenbankuser einzugeben.
`Downloading latest Easy-WI Stable version.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 4188k    0 4188k    0     0  2977k      0 --:--:--  0:00:01 --:--:-- 3807k
Unpack zipped Easy-WI archive.
Creating database easy_wi and connected user easy_wi
Enter password:
`

Am Ende der Installation wurde anscheinend das Kennwort überschrieben??
`Easy-WI Webpanel setup is done regarding architecture. Please open http://<IP>/install/install.php and complete the installation dialog.
DB user and table name are "easy_wi". The password is "<PASSWORT-was-ich-nicht-eingegeben-habe>".`

In der anschließenden Einrichtung über den Browser funktioniert auch nur das Kennwort, welches am Ende des Installers angezeigt wird. Nicht das was ich eingegeben habe.

**Comment by Lacrimosa99** [comment]
Es wird aus Sicherheitsgründen ein Random Kennwort erstellt, welches aber nur für den WI Nutzer ist.
Dies soll die Sicherheit des Users erhöhen.

**Comment by Mitleidleggins** [comment]
Aha, ok.
Also ist dieser Zwischenschritt mit dem Kennwort eingeben komplett irrelevant?

**Comment by Lacrimosa99** [comment]
Nein da ja eine Datenbank bzw der Datenbank Server schon bestand.
Diese Abfrage kommt nur bei bestehenden Datenbank Servern, da das Script das DB Kennwort nicht kennen kann.

**Comment by Mitleidleggins** [comment]
Ok, alles klar. Danke.
