### ISSUE TITLE
mariadb-server installer not working!

### ISSUE THREAD

**Issue by DJJeffP** [easy-wi/installer#77]
Hi,

When I use the installer and come to the part where it should install the MySQL mariadb-server it gets a error:

> Installing package mariadb-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  galera-3 gawk libcgi-fast-perl libcgi-pm-perl libfcgi-perl libhtml-template-perl libsigsegv2 mariadb-server-10.3 mariadb-server-core-10.3 rsync socat
Suggested packages:
  gawk-doc libipc-sharedcache-perl mailx mariadb-test netcat-openbsd tinyca
The following NEW packages will be installed:
  galera-3 gawk libcgi-fast-perl libcgi-pm-perl libfcgi-perl libhtml-template-perl libsigsegv2 mariadb-server mariadb-server-10.3 mariadb-server-core-10.3 rsync socat
0 upgraded, 12 newly installed, 0 to remove and 1 not upgraded.
Need to get 11.2 MB/23.1 MB of archives.
After this operation, 173 MB of additional disk space will be used.
Err:1 http://mirror.netcologne.de/mariadb/repo/10.2/debian buster/main amd64 galera-3 amd64 25.3.25-buster
  404  Not Found [IP: 194.8.197.22 80]
E: Failed to fetch http://mirror.netcologne.de/mariadb/repo/10.2/debian/pool/main/g/galera-3/galera-3_25.3.25-buster_amd64.deb  404  Not Found [IP: 194.8.197.22 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
./easy-wi_install.sh: line 208: /etc/init.d/mysql: No such file or directory

> Securing MySQL by running "mysql_secure_installation" commands.

> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

> ./easy-wi_install.sh: line 208: /etc/init.d/mysql: No such file or directory

> Error: No SQL server running but required for Webpanel installation.

I'm running OS Debian 10, and the Developer Version of the Easy-Wi installer to work with Debian 10. 

`wget https://raw.githubusercontent.com/easy-wi/installer/master/easy-wi_install.sh`
`bash ./easy-wi_install.sh`

How can I fix this so it is installing the Mariadb-server correctly? I did a check on the links for the mariadb and those are not existing anymore.

Thank you in advanced

**Comment by MikkelDK** [comment]
Sorry for the delay!

It's better you are contacting us on Discord.

```
Err:1 http://mirror.netcologne.de/mariadb/repo/10.2/debian buster/main amd64 galera-3 amd64 25.3.25-buster
404 Not Found [IP: 194.8.197.22 80]
E: Failed to fetch http://mirror.netcologne.de/mariadb/repo/10.2/debian/pool/main/g/galera-3/galera-3_25.3.25-buster_amd64.deb 404 Not Found [IP: 194.8.197.22 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

As you see here: It will not install it. because it can't get contact with the mirror server! :)

**Comment by DJJeffP** [comment]
That is was what I discovered already, I quote :

> I did a check on the links for the mariadb and those are not existing anymore.

But is there a way to fix that? I had to do it by hand to install the db. But can not true the installer. Is there a way that we can do it still true the installer? has somebody has a fix for that?

**Comment by MikkelDK** [comment]
What about mysql-server ?

**Comment by DJJeffP** [comment]
There was no option for me to choose between MySQL or MariaDB, I have now a manual installed MySQL Database on my test server. 
But I can understand that dev's who want to use the installer want to use it true the installer. A specially when you need to do multiple servers.

**Comment by Lacrimosa99** [comment]
is fixed with new mirror.
sorry for delay -.-
