### ISSUE TITLE
Install Script - Change PHP Version to 7.3

### ISSUE THREAD

**Issue by PacWhite** [easy-wi/installer#78]
On the new Debian 10 it comes to some Problems with the Installer. The Setup tries to install PHP7.0 but this is not in the normal repo of Debian. It should be change to **7.3.** 

I change it manually in the install script in this lines.
![image](https://user-images.githubusercontent.com/6573126/65143036-4d254500-da14-11e9-9603-deb476eb97ac.png)

![image](https://user-images.githubusercontent.com/6573126/65143066-5e6e5180-da14-11e9-8154-fd8ac3d20f7b.png)

**Comment by Lacrimosa99** [comment]
Use the Unstable Installer.
Fixed in https://github.com/easy-wi/installer/commit/82010295606948bf72750b92252ebd2c7d117132
