### ISSUE TITLE
Debian 10 MySQL Server installing fails.

### ISSUE THREAD

**Issue by PacWhite** [easy-wi/installer#79]
It needs to be "Pre" Installed Mariadb-server that the installer works correctly on debian 10. I dont know if this was my fault or that of the installer. The error appears only by installing WebPanel. 

The Installer tries to use the command mysql and it fails but it is not installed.

**Comment by Lacrimosa99** [comment]
Debian 10 is not full supported... we working on it.

**Comment by thhunder** [comment]
it fails on the netcologne mirrors of mariadb maybe it will be enough to remove the mirrors because on debian and ubuntu you don't need third-party mirrors to install mariadb to get it to work on deb. 10?

**Comment by Lacrimosa99** [comment]
fixed https://github.com/easy-wi/installer/commit/648ee83a5bc011cdcb89a3bbb9a08eefeb4c79e5
