### ISSUE TITLE
nginx support (Option choose between apache2/nginx)

### ISSUE THREAD

**Issue by MikkelDK** [easy-wi/installer#81]
**_It could be nice if the installer did support Nginx._**

**Easy-Wi Panel = supporting apache2, but it doesn't support Nginx (which it should do)**

**Comment by Spacelord09** [comment]
Nginx :heart:

**Comment by AEon-Jan** [comment]
The installer is Apache only that is right!

But you can Install the panel manually on NGINX if you want.
You need a Database / Nginx / PHP 
https://easy-wi.com/en/faq/conditions/
