### ISSUE TITLE
CentOS 7 Error with lib32tinfo5 

### ISSUE THREAD

**Issue by ChiefMcClane** [easy-wi/installer#89]
**Installing package lib32tinfo5**
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.alpix.eu
 * epel: mirror.de.leaseweb.net
 * extras: mirror.alpix.eu
 * remi-php73: mirror.23media.com
 * remi-safe: mirror.23media.com
 * rpmforge: mirror1.hs-esslingen.de
 * updates: centosmirror.netcup.net
No package lib32tinfo5 available.
Error: Nothing to do

**Please check Output!
Installation abort!**

**Comment by R3belWithoutAPause** [comment]
What version of CentOS is this please  and what were you trying to do when this error happened ?

I can't test on CentOS right now but i will get to this. If you can give me the requested information i will see about why this happens and look at a fix

**Comment by R3belWithoutAPause** [comment]
Just tested this on my CentOS7 VM and indeed lib32tinfo5 doesn't exist. Open the script and browse to around line 2150 and you should see this:

`if [ "$(uname -m)" == "x86_64" ]; then
        okAndSleep "Installing 32bit support for 64bit systems."
	checkInstall glibc.i686
	checkInstall libstdc++.i686
	checkInstall lib32tinfo5
fi
checkInstall libgcc`

Just remove/comment the checkInstall lib32tinfo5 line. Gameserver root installed fine for me after doing this. I will push this fix to the developer build.

**Comment by AEon-Jan** [comment]
Will be fixed within the next update ...

**Comment by Nexus633** [comment]
updated
