### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by GLITCH-Jan** [easy-wi/installer#90]
Ubuntu 20.04, unstable Installer versucht PHP 7.2 / 7.0 zu installieren.
Da beides Veraltet ist schlägt entsprechende Installation fehl.
![unknown](https://user-images.githubusercontent.com/31162382/82156146-ce6df980-9879-11ea-8a83-ffe9b08f3459.png)

**Comment by R3belWithoutAPause** [comment]
Hi,
I just made a PR which should address this in my own testing
The problem is that Ubuntu 20.04 uses PHP7.4 and there was no support for this in the installer script. I have updated it to fix this problem:
[https://github.com/easy-wi/installer/pull/92](url)

**Comment by Lacrimosa99** [comment]
https://github.com/easy-wi/installer/commit/4caad34d4c519cab1cbc2cd9b3f28fc7028801d0
