### ISSUE TITLE
MariaDB / MySQL Issue Public Key

### ISSUE THREAD

**Issue by AEon-Jan** [easy-wi/installer#96]
TO-DO: Repos need an update!

![firefox_2020-07-22_21-14-17](https://user-images.githubusercontent.com/31162382/88219026-3b7a8280-cc61-11ea-8379-4ad0bb37c1a9.png)

**Comment by Lacrimosa99** [comment]
Public Key wird nur nicht sauber Importiert... schau mir die betreffende Stelle noch bei Gelegenheit an.
