### ISSUE TITLE
LOCAL_IP output = 0

### ISSUE THREAD

**Issue by NXTOnline** [easy-wi/installer#97]
Wrong output on external IP.

Currently the output = 0 instead of the external IP

Line 114
> LOCAL_IP=`ip route get 8.8.8.8 | awk '{print $NF; exit}'`

changed to 
> LOCAL_IP=`ip route get 8.8.8.8 | awk '{print $7; exit}`

than fixed

**Comment by NXTOnline** [comment]
Kleine Korrektur... 
in der Aktuelleb Version ist das in der Zeile 389

**Comment by Nexus633** [comment]
sollte die ausgabe 0 lauten, prüft der installer die ip anhand des Hostnames.
